### ISSUE TITLE
Only this version with these settings is working for me

### ISSUE THREAD

**Issue by czerwinski76** [dqx-translation-project/dqxclarity#249]
v4.8.8 with no update.

![20-07-2024_190213](https://github.com/user-attachments/assets/02371622-bf42-4152-85e9-8279f03689a0)

The newest versions always give me a CMD windows who is closing by itself and nothing is coming.
Plus "run_clarity.ps1 is missing" on second launch.

**Comment by jmctune** [comment]
Hi there,

dqxclarity relies on memory patterns for certain functionality to work (NPC names, player names, monster names to name a few.) We're always chasing changes, so using older versions isn't going to work.

As for files missing, this will almost certainly be due to your anti-virus deleting files. Ensure you're adding an exception in your anti-virus to the entire dqxclarity directory.

If you're pressing run and you see a window open and then close, there's an error occurring somewhere when attempting to launch.

I would start by downloading the latest version again, adding the anti-virus exception to the folder and then running the program again.

If you still have issues, we can try running the program manually from the command prompt to see what might be occurring. To do this:

- Open a command prompt as administrator on your computer
- Navigate to the dqxclarity directory by typing this command: `cd <path_to_dqxclarity_directory>`
- Run the launch script: `
powershell.exe -ExectionPolicy Bypass -File run_clarity.ps1 -ClarityArgs -cpn`

This should be enough to tell us what's going on. Please provide as many screenshots as possible to help with figuring out what's going on, including error messages.

**Comment by czerwinski76** [comment]
Thank you for replying me quickly @jmctune jmctune.

![21-07-2024_015930](https://github.com/user-attachments/assets/68cb1aab-232e-4162-ac64-082b71e560d1)

This is a strange problem.

Powershell is working nicely on 4.8.8.

**Comment by jmctune** [comment]
There is a typo. It should be `ExecutionPolicy` (you have `ExectionPolicy`).

**Comment by czerwinski76** [comment]
![21-07-2024_022153](https://github.com/user-attachments/assets/7a02a9ef-23f2-4ebe-b22a-f6f1e35da38a)

I think it's OK now.

My antivirus software had deleted run_clarity.ps1.

**Comment by jmctune** [comment]
Great, that looks good. With the anti-virus exception, everything should be working correctly.

If you're still having issues, let me know.

**Comment by czerwinski76** [comment]
![21-07-2024_023051](https://github.com/user-attachments/assets/49e91c63-87c6-4425-b8d2-bf1cba2d6f86)

Thank you for your help jmctune.
Have a good day ! 🙂.
