### ISSUE TITLE
Power shell script error after clicking on run

### ISSUE THREAD

**Issue by githubnowx21** [dqx-translation-project/dqxclarity#261]
I been getting power shell script error after clicking on the run tab button. 

I uploaded an image, please help, as during the power shell phase, its not just python wants to get downloaded and installed, but also the DQ10 dependencies, which is needed,  thanks.

![DQ10 Clarity - Power shell script error](https://github.com/user-attachments/assets/c2ec2fc1-4d08-4be0-88da-39e0c67550cd)

If you all have problems viewing the above image, please click on the direct link down below:

https://ibb.co/PCKZp2H

**Comment by githubnowx21** [comment]
Ok, I got everything to work now, with a help of one of our forum members.

For anyone who is having this very stingy issue, here is how to fix it:

This is for the latest version of DQ10 Clarity:

1st, download this particular python: https://www.python.org/ftp/python/3.11.3/python-3.11.3.exe

Next, put the file within the DQ10 folder, then run cmd under admin, then type this below:

CD "Location of your DQ10 Clarity .exe file"
.\python-3.11.3.exe /passive InstallAllUsers=1 PrependPath=1 Include_doc=0 Include_tcltk=1 Include_test=0 Shortcuts=0 SimpleInstallDescription="Installing necessary components for dqxclarity.

Finally run Clarity with admin rights, now it will start downloading the DQ10 Dependencies, logged into the game, everything works perfectly.

**Comment by jmctune** [comment]
Hey @githubnowx21. Sorry for the delayed response.

This isn't really a clarity issue, but a problem with either the local SSL certificates installed on your computer or the way your computer is attempting to make a secure connection to Python's FTP (maybe using an insecure or unsupported version of SSL). Just as a heads up, the above installation is just a workaround and not a fix to the underlying problem.

This is a common problem that would need further troubleshooting to figure out what's going on:

https://duckduckgo.com/?t=ffab&q=invoke-webrequest+could+not+create+secure+ssl%2Ftls+channel&ia=web

That python installation command is the same command that clarity uses to install Python:

https://github.com/dqx-translation-project/dqxclarity/blob/main/app/run_clarity.ps1#L50

so that wouldn't cause any further issues using clarity.

Regardless, I'm glad you've got it working now. I'll go ahead and close this.
